### ISSUE TITLE
Wrong content at readme file

### ISSUE THREAD

**Issue by baskvava** [Adufe-Obanijesu/furniture-website#1]
Hi ,
I notice that the readme file content is not the furniture-website.

**Comment by Adufe-Obanijesu** [comment]
Wowww...I can't believe what I'm seeing. I really appreciate you for the
update. I copied the folder of a project and used it because internet
access is kind of expensive here and I totally forgot about the readme.
Thanks once again. I will look into it tonight

I don't know if you mind chatting up with me on LinkedIn. I could learn a
thing or two from the master

**Comment by Adufe-Obanijesu** [comment]
https://www.linkedin.com/in/obanijesu-adufe

Here's the link if you don't mind
